### ISSUE TITLE
GitHub dependency leading to startup issues

### ISSUE THREAD

**Issue by Pulz-TCP** [HrznStudio/Emojiful#12]
Hi, can some kind of adjustment please be made so that this mod does not require some form of connection to GitHub- as it means that any modpack with the mod cannot launch whenever there are GitHub issues.

**Comment by Lanse505** [comment]
The 1.12 release is EOL (End of Life) and won't receive any further updates.
A rewrite has been looked into for 1.15, however with the unicode change coming in 1.16 and the fact this mod is not a priority. The outcome looks slim.
